# Generated by Django 3.1.7 on 2021-03-27 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_num', models.CharField(blank=True, max_length=20, verbose_name='reg_munber')),
                ('vin', models.CharField(blank=True, max_length=20, verbose_name='vin_munber')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='Manifactures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_manifactures', models.CharField(max_length=200, verbose_name='maifactures')),
            ],
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_repair', models.CharField(max_length=200, verbose_name='rapair description')),
                ('date_repair', models.DateTimeField(auto_now_add=True, verbose_name='date repair')),
                ('car_repair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.car')),
            ],
        ),
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_work', models.CharField(max_length=200, verbose_name='title work')),
                ('price_patr', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='price part')),
                ('repair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.repair')),
            ],
        ),
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_part', models.CharField(max_length=200, verbose_name='title part')),
                ('price_patr', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='price part')),
                ('repair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.repair')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='manifactures',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.manifactures'),
        ),
    ]
