# Generated by Django 3.1.7 on 2021-03-27 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=100, verbose_name='first name')),
                ('l_name', models.CharField(blank=True, max_length=100, verbose_name='last name')),
                ('phone', models.CharField(blank=True, max_length=100, verbose_name='phone')),
                ('owner_data', models.TextField(verbose_name='description owner')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='owner_car',
            field=models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, to='car.owner'),
            preserve_default=False,
        ),
    ]
